### ISSUE TITLE
CocoaPods issue

### ISSUE THREAD

**Issue by olddonkey** [ApplikeySolutions/VegaScroll#1]
Error during `pod install`

> [!] No podspec found for `VegaScrollFlowLayout` in `https://github.com/AppliKeySolutions/VegaScroll.git`

**Comment by AppliKey** [comment]
Try:
pod repo update

**Please check if the platform in your Podfile compatible with the spec's minimum deployment target.**

**Comment by mifanj** [comment]
我也遇到同样的问题，最后将podfile中的指向源地址的配置删了，改成pod 'VegaScrollFlowLayout', '~> 1.0'，重新pod install 问题解决。希望能帮到你。

**Comment by olddonkey** [comment]
谢谢
