### ISSUE TITLE
Cells moving

### ISSUE THREAD

**Issue by antoinebell** [ApplikeySolutions/VegaScroll#13]
When I scroll through the cells, they start doing a circular movement faster and faster after a few scrolls.
See it in video here : [http:/tinypic.com/r/110wzso/9](http:/tinypic.com/r/110wzso/9)

Is it normal ? I was not able to reproduce this in the Example project.

**Comment by heysaik** [comment]
Yeah. I've had the same problem too. Can there please be a fix for this?!

**Comment by dillidon** [comment]
@antbelldev @aidev1065 just comment two lines:
``` Swift
springBehaviour.damping = 0.8
springBehaviour.frequency = 1.0
```

**Comment by antoinebell** [comment]
@dillidon Working perfectly, thank you !
