### ISSUE TITLE
iPhone X Simulator layout bug

### ISSUE THREAD

**Issue by sigursalt** [ApplikeySolutions/VegaScroll#4]
The cells oscillate wildly left/right/up/down on the XCode 9 (GM) iPhone X simulator with the example project (just whip the collection view up and down a couple of times).

I created a new project and it does the same thing for mine.  

I would imagine this is a simulator bug, but wanted to make sure it was on your radar.

Great library, btw!

**Comment by AppliKey** [comment]
Hi,

Thanks for reaching us. We can confirm it or deny only when we have iPhone X on our hands to test. So we have to wait until NOV. 

BR,
Applikey team

**Comment by LivioGama** [comment]
Same on this lib https://github.com/roberthein/BouncyLayout

**Comment by FreitDev** [comment]
Anyone else that wants a simple fix for this issue... I added this
` - collectionView.frame.width.truncatingRemainder(dividingBy: 2)`
to my width and it worked. Thanks guys!
