### ISSUE TITLE
Perform strange when changing item width

### ISSUE THREAD

**Issue by hstdt** [ApplikeySolutions/VegaScroll#6]
iPad Pro, iOS 11.0

![vegascroll](https://user-images.githubusercontent.com/10215098/31329500-0014ccbc-ad0d-11e7-9aea-4cea772b2a53.gif)

**Comment by LivioGama** [comment]
Funny, I have the same issue with https://github.com/roberthein/BouncyLayout on iPhone X simulator, iOS 11.0
![sans titre](https://user-images.githubusercontent.com/6930498/31469260-6cbb69d6-aee1-11e7-9535-48e90c9d9c87.gif)

**Comment by altjordao** [comment]
Hi!
I think i know the problem. So to do the bounce animation the code is using UIDynamicAnimator if you are using float values to define the width of the cells when the physics engine is calculating the positions for the cells you will have some problem with rounding that values and over time the value rounded will increase.

To fix this try setting cell sizes with round values, like 200 not 200,34782.

Hope this will help!

**Comment by hstdt** [comment]
@altjordao  Thank you. `let itemWidth = ( UIScreen.main.bounds.width / 3 - 2 * xInset).rounded(.towardZero)` works well.

**Comment by emgbtg** [comment]
you need to round to the nearest whole **even** number 
`round(value / 2.0)) * 2`
